services:
    client:
        container_name: debug_dev_client2
        build: ./client
        image: debug_client
        ports:
            - 8080:8080
        working_dir: /code
        volumes:
            - type: bind
              source: ./client
              target: /code
        command: ["http-server"]
    api:
        container_name: debug_dev_api2
        ports:
            - 3000:3000
        environment:
            - PGUSER=hassan_stefan
            - PGHOST=db
            - PGPASSWORD=librarypass
            - PGDATABASE=library
            - PGPORT=5432
            - NODE_ENV=development
        depends_on:
            - db
        command: bash -c "npm install && npm run seedDev && npm run dev"

    db:
        container_name: debug_dev_db
        volumes:
            - "dbdata:/var/lib/postgresql/data"
        environment:
            - POSTGRES_DB=library
            - POSTGRES_USER=hassan_stefan
            - POSTGRES_PASSWORD=librarypass
volumes:
    dbdata:
networks:
    default:
        name: debug_api
